#!/bin/ruby

if ARGV.empty? 
    puts "please specify the artifactId"
end

artifactId = ARGV[0]

template =<<EOM
<?xml version='1.0' encoding='UTF-8'?>
<project 
xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
xsi:schemaLocation='http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd' 
xmlns='http://maven.apache.org/POM/4.0.0'>

    <modelVersion>4.0.0</modelVersion>
    <groupId>org.thought-tracker</groupId>
    <artifactId>#{artifactId}</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    
    <parent>
        <groupId>org.thought-tracker</groupId>
        <artifactId>scala-builder-pom</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <dependencies>
    </dependencies>
</project>
EOM

require 'fileutils'

['scala', 'resources'].each { |leaf| 
    FileUtils.mkdir_p "#{artifactId}/src/main/#{leaf}"
    FileUtils.mkdir_p "#{artifactId}/src/test/#{leaf}"
}

File.open("#{artifactId}/pom.xml", "w") { |file|
    file << template
}

